services:
  - type: web
    name: iot-webapp
    env: node
    plan: free
    buildCommand: npm install && npm run build:frontend
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: iot-webapp
          property: port